"""Minimal local stub for ddgs.exceptions; see ddgs/__init__.pyi for rationale."""

class DDGSException(Exception): ...
class RatelimitException(DDGSException): ...
class TimeoutException(DDGSException): ...
