// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Admission/queue aggregates for `/api/stats` (W1-09). Sourced from the
 * in-process metrics registry by `StatsSnapshot::merge_metrics`; store
 * impls emit it zeroed. Counts are per request (every waiter on a flight
 * observes the same rejection/stale outcome) except `deadline_hits`, which
 * is per flight — the deadline cuts the shared fan-out once.
 */
export type AdmissionStats = { 
/**
 * Flight leader acquires that measured a bounded-queue wait
 * (`cauce_admission_wait_ms` observations).
 */
waits: number, wait_median_ms: number, wait_p80_ms: number, wait_p95_ms: number, 
/**
 * Requests rejected by admission (`cauce_admission_rejected_total`).
 */
rejected: number, 
/**
 * Rejections split by `reason` label (`queue_full`, `wait_timeout`).
 */
rejected_by_reason: Record<string, number>, 
/**
 * Flights cut by the hard deadline (`cauce_deadline_hit_total`,
 * per flight — shared across the flight's waiters).
 */
deadline_hits: number, 
/**
 * Responses served from an expired cache row
 * (`cauce_stale_served_total`).
 */
stale_served: number, };
