// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[admission]`: singleflight + bounded per-engine queue (parent plan
 * 6.2, W1-07).
 */
export type AdmissionConfig = { 
/**
 * Total milliseconds a request may wait for per-engine slots before
 * admission overflows to a stale row or a 429. Default 1500.
 */
max_wait_ms: number, 
/**
 * Concurrent upstream calls allowed per engine id. Default 3 matches
 * the per-engine politeness burst (1 req/s burst 3).
 */
max_concurrent_per_engine: number, };
