// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProtocol } from "./AiProtocol";

/**
 * `[ai]`: provider settings plus the answer loop's budget knobs (#233).
 * `base_url`/`api_key` are empty strings by default, not a reference to
 * anyone's local gateway; point them at an OpenAI-compatible endpoint
 * (e.g. an `api_key = "${env:...}"` template) to use them.
 */
export type AiConfig = { 
/**
 * OpenAI-compatible endpoint.
 */
base_url: string, 
/**
 * API key or a `${env:...}`/`${file:...}` template.
 */
api_key: string, 
/**
 * Provider model name (W4 settled inputs); empty until one is chosen.
 */
model: string, 
/**
 * Master switch; `false` until W4.
 */
enabled: boolean, 
/**
 * Wire protocol the provider client speaks (W4 settled inputs):
 * `openai` (default, `chat/completions`) or `anthropic` (`/v1/messages`).
 */
protocol: AiProtocol, 
/**
 * Provider turns the answer loop may take before it must synthesize
 * (#231's `LoopConfig::max_turns`; a forced-synthesize turn rides on
 * top, so the run is bounded at `max_turns + 1` provider calls).
 */
max_turns: number, 
/**
 * Tool calls the answer loop may execute per run (#231's
 * `LoopConfig::max_search_executions`): repeated or over-budget calls
 * resolve in-band for free, so this is the real cost budget.
 */
max_searches: number, 
/**
 * Per-call provider timeout in seconds, applied to every `chat_stream`
 * invocation (#231's `LoopConfig::provider_budget`). Must be >= 1.
 */
provider_budget_s: number, 
/**
 * Reserved for the marginal-groundedness verifier (#232): parsed and
 * hot-reloaded like the rest of `[ai]` but not yet consulted.
 */
verify: boolean, 
/**
 * PUB-03: honour per-request `ai.api_key`/`model`/`protocol`
 * overrides on `POST /api/answer` — bring-your-own-key callers pay
 * their own provider account instead of the instance's.
 */
allow_user_keys: boolean, 
/**
 * PUB-03: also honour a per-request `ai.base_url` override. Kept a
 * separate gate because an open base_url turns the instance into
 * an egress relay.
 */
allow_user_base_url: boolean, 
/**
 * PUB-03: per-client-IP daily budget for answers the admin's `[ai]`
 * config pays for; `0` is unlimited — on a public instance with
 * `[ai]` set, leaving it unset is the operator's explicit
 * free-for-everyone choice. BYOK requests never consume it.
 */
free_daily_answers: number, };
