// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiProtocol } from "./AiProtocol";

/**
 * The per-request `ai` override object on `POST /api/answer` (PUB-03):
 * every field optional and gated before the merge — the credential
 * triple (`api_key`/`model`/`protocol`) needs `allow_user_keys`,
 * `base_url` needs `allow_user_base_url`. Merged fields apply over the
 * loaded `[ai]` config for that request only.
 */
export type AiOverride = { 
/**
 * The caller's own provider key — its presence makes the request
 * BYOK: it bills the caller's provider account and skips the
 * `free_daily_answers` budget entirely.
 */
api_key: string | null, 
/**
 * Model name override.
 */
model: string | null, 
/**
 * Provider protocol override (`openai`/`anthropic`).
 */
protocol: AiProtocol | null, 
/**
 * Endpoint override — an open base_url is an egress relay, so it
 * needs `allow_user_base_url` on top of `allow_user_keys`.
 */
base_url: string | null, };
