// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `[ai].protocol` vocabulary (W4-05): which provider client the
 * AI surface builds. An unknown value fails config load.
 */
export type AiProtocol = "openai" | "anthropic";
