// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerSource } from "./AnswerSource";

/**
 * One item of the `stream_answer` channel — the settled W4-02 wire
 * shapes, serde-tagged on `type` so SSE is `data: {"type": ...}`.
 */
export type AnswerFrame = { "type": "step", tool: string, query: string, label: string, } | { "type": "delta", text: string, } | { "type": "sources", sources: Array<AnswerSource>, } | { "type": "done", answer: string, confidence: number, model: string, related_questions: Array<string>, 
/**
 * `true` only on the `answers`-table replay.
 */
cached: boolean, 
/**
 * The inbound request id (supplied or minted UUIDv7).
 */
request_id: string, 
/**
 * `true` when the answer drew on no sources; absent otherwise.
 * (`default` is inert — `AnswerFrame` is never deserialized — but
 * tells ts-rs the field may be absent on the wire.)
 */
ungrounded?: boolean, } | { "type": "error", message: string, 
/**
 * Provider retry hint, only on rate limits.
 */
retry_after_s?: number, };
