// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";

/**
 * One cited source: an item of the `sources` frame (W4-02 settled wire
 * shape) and of `answers.sources_json`.
 */
export type AnswerSource = { url: string, title: string, snippet: string, engine: EngineId, };
