// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerSource } from "./AnswerSource";
import type { AnswerStatus } from "./AnswerStatus";
import type { ClientKind } from "./ClientKind";
import type { SearchOrigin } from "./SearchOrigin";

/**
 * `answer_log` row (#254): the durable, non-TTL'd record of one
 * terminal `stream_answer` run — the human-facing counterpart of
 * `search_log` for questions asked in AI mode. Written by
 * `AnswerLoop::run` on every terminal path; `id` is `None` on insert.
 */
export type AnswerLogRow = { id: number | null, ts: string, 
/**
 * The normalized question (`normalize_query`), matching `search_log`.
 */
query: string, 
/**
 * The question exactly as submitted, for history displays.
 */
query_raw: string | null, 
/**
 * Model the answer ran on (`done.model`, else the provider's).
 */
model: string, 
/**
 * The answer markdown; empty on `status = error` rows.
 */
answer: string, 
/**
 * The verbalized confidence (display only); absent on error rows.
 */
confidence: number | null, 
/**
 * The cited source set (`sources_json` column).
 */
sources: Array<AnswerSource>, 
/**
 * The `related_questions` tail (`related_json` column).
 */
related_questions: Array<string>, 
/**
 * The inbound request id (`done.request_id`).
 */
request_id: string | null, 
/**
 * The inbound surface's client, same convention as `search_log`.
 */
client: ClientKind, 
/**
 * `user` iff `client == Ui` — the human's own question; `agent`
 * for api/mcp/cli-driven runs.
 */
origin: SearchOrigin, status: AnswerStatus, 
/**
 * `done.ungrounded` — the answer drew on no sources.
 */
ungrounded: boolean, 
/**
 * The terminal error message on `status = error` rows.
 */
error: string | null, };
