// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerRole } from "./AnswerRole";

/**
 * One prior turn of an `/answer` thread (W7-04): `{role, content}` as
 * the page echoes it back — `content` is the submitted question for
 * `User`, the `done.answer` text (metadata tail already stripped) for
 * `Assistant`.
 */
export type AnswerTurn = { role: AnswerRole, content: string, };
