// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiOverride } from "./AiOverride";
import type { AnswerSource } from "./AnswerSource";
import type { AnswerTurn } from "./AnswerTurn";

/**
 * The `POST /api/answer` body; unknown fields are rejected like the
 * query-side `deny_unknown_fields` contract.
 */
export type AnswerBody = { q: string, 
/**
 * W7-02 Search Assist: the result set the caller already has (the
 * SERP's top rows). Present — even empty — selects
 * [`cauce_agent::AnswerLoop::stream_assist`]: a single no-tools turn
 * grounded in these results, never an engine re-fetch. Absent runs
 * the full tool loop.
 */
context_results: Array<AnswerSource> | null, 
/**
 * W7-04 conversation threads: the prior completed turns of this
 * `/answer` thread, oldest first — strict `user`/`assistant` pairs
 * ending on an assistant turn (the new `q` follows). The page owns
 * the thread; the loop replays it to the provider verbatim.
 * Mutually exclusive with `context_results`: assist stays
 * single-turn.
 */
history: Array<AnswerTurn> | null, 
/**
 * PUB-03 BYOK override: merged over the loaded `[ai]` config under
 * its gates (`ai.allow_user_keys`, `ai.allow_user_base_url`) — a
 * request carrying its own `api_key` bills the caller's provider
 * account and never touches the `free_daily_answers` budget.
 */
ai: AiOverride | null, };
