// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An API error rendered as the `{error: {...}}` envelope.
 *
 * `request_id` is stamped by the handler's [`RequestCtx`] helpers
 * (`ctx.bad_request(...)` etc.) so the envelope id always equals the
 * `X-Request-Id` response header.
 *
 * [`RequestCtx`]: crate::middleware::RequestCtx
 *
 * The TypeScript shape is the emitted envelope (`envelope()`), not the
 * field set — `status` rides the response line, `retry_after_s` the
 * `Retry-After` header, so neither appears in the body.
 */
export type ApiError = { error: { code: string, message: string, request_id: string | null } };
