// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One archive row on the JSON wire: a `PageHit` with its snippet's
 * `PAGE_MARK_*` delimiters stripped (the marks are the HTML contract,
 * not part of the wire text).
 */
export type ArchiveRow = { url: string, title: string, snippet: string, fetched_at: string, score: number | null, };
