// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveRow } from "./ArchiveRow";

/**
 * `GET /api/archive` envelope (`{query,limit,offset,has_more,results,
 * request_id}`) — the `/api/search` envelope's convention: request id
 * top level, results carrying `{url,title,snippet,fetched_at[,score]}`.
 */
export type ArchiveResponse = { 
/**
 * The `?q=` text as typed; `null` on the browsing arm.
 */
query: string | null, 
/**
 * Page size the request resolved to.
 */
limit: number, 
/**
 * `?offset=` the request resolved to.
 */
offset: number, 
/**
 * A further page exists.
 */
has_more: boolean, 
/**
 * `limit` hits in bm25 rank order (search arm) or newest first
 * (browsing arm).
 */
results: Array<ArchiveRow>, 
/**
 * The request id (`RequestCtx`).
 */
request_id: string, };
