// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[archive]` (W5-01): the fetch-and-index pipeline behind
 * `POST /api/pages`, the UI click beacon and MCP `fetch_and_index`.
 */
export type ArchiveConfig = { 
/**
 * Whether clicking a result link in the UI fires the indexing beacon
 * (default true, settled input). The beacon is failure-silent and
 * never blocks the navigation either way.
 */
index_on_click: boolean, 
/**
 * Host-keyed token-bucket refill rate for archive fetches (>= 1).
 * Conservative by default so archive traffic never starves engine
 * fan-out.
 */
requests_per_second: number, 
/**
 * Host-keyed token-bucket burst capacity (>= 1).
 */
burst: number, 
/**
 * Skip the SSRF egress guard (default false): when true the fetcher
 * may dial private/reserved addresses (loopback, RFC 1918,
 * link-local). A documented opt-in for indexing local services —
 * `POST /api/pages` and MCP `fetch_and_index` stay open to
 * server-side request forgery while it is on.
 */
allow_private: boolean, };
