// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * `audit` row (section 5): attributed admin/AI/MCP events.
 *
 * `actor` follows the `ui | api | mcp:<client> | cli` convention
 * (`ClientKind::label()`), with an optional `X-Actor` override string.
 */
export type AuditRow = { id: number | null, 
/**
 * Server always fills this on write; the serde default exists only so a
 * caller-built row can omit it.
 */
ts: string, actor: string, 
/**
 * e.g. `cache.delete`, `config.put`, `engine.reset`.
 */
action: string, 
/**
 * What was acted on (cache key, engine id, config path).
 */
target: string, 
/**
 * Free-form structured details (`details_json` column).
 */
details: JsonValue, request_id: string | null, };
