// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[auth]`: the admin-auth switch (W1-13). The token mechanism itself is
 * deferred to `v3/later/postgres-and-multi-instance.md`; until it lands,
 * `enabled` is forced by the bind address — off on loopback, required off
 * it, so `cauce serve` refuses a non-loopback bind.
 */
export type AuthConfig = { 
/**
 * Master switch. Forced `true` when the bind is not loopback (see
 * [`AuthConfig::enabled_for`]); ignored on loopback until token auth
 * exists, so setting it only earns a startup warning.
 */
enabled: boolean, };
