// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[auth]`: the admin-auth switch (W1-13) plus FX-07's admin credentials.
 * `enabled` is forced by the bind address — off on loopback, required off
 * it, so `cauce serve` refuses a non-loopback bind until full token auth
 * lands (`v3/later/postgres-and-multi-instance.md`).
 */
export type AuthConfig = { 
/**
 * Master switch. Forced `true` when the bind is not loopback (see
 * [`AuthConfig::enabled_for`]); ignored on loopback until token auth
 * exists, so setting it only earns a startup warning.
 */
enabled: boolean, 
/**
 * Static admin bearer tokens (FX-07): on a `public_instance` the
 * `Authorization: Bearer <token>` credential that earns `role: "admin"`
 * on `/api/*` requests. Tokens carry no id today — audit rows keep
 * recording `X-Actor`/client kind; token-id hashes arrive with the
 * deferred W6-03 item. Empty (the default) means the admin surface is
 * unreachable on a public instance — deliberate fail-closed.
 */
admin_tokens: Array<string>, };
