// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[auth]`: the admin credentials FX-07 wired to `RouteAuth::Admin`.
 * `enabled` is the vestigial W1-13 switch: the real boundary is now
 * `server.public_instance` (see [`ServerConfig::check_bind`]), so the
 * flag no longer does anything — it is still parsed for file compat
 * and earns a startup warning when set.
 */
export type AuthConfig = { 
/**
 * Superseded by `server.public_instance` (PUB-01). Parsed for file
 * compat; a set value warns at `cauce serve` startup.
 */
enabled: boolean, 
/**
 * Static admin bearer tokens (FX-07): on a `public_instance` the
 * `Authorization: Bearer <token>` credential that earns `role: "admin"`
 * on `/api/*` requests. Tokens carry no id today — audit rows keep
 * recording `X-Actor`/client kind; token-id hashes arrive with the
 * deferred W6-03 item. Empty (the default) means the admin surface is
 * unreachable on a public instance — deliberate fail-closed.
 */
admin_tokens: Array<string>, };
