// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * sha256 hex digest identifying a cacheable request.
 *
 * Canonical preimage (section 4.2): sha256 over a length-prefixed binary
 * tuple, fields in fixed order:
 *
 * ```text
 *   normalize_query(q)                    u32le len + utf8
 *   page                                  u8
 *   lang                                  0x00 | 0x01 + u32le len + utf8
 *   time_range                            0x00 | 0x01 + u8 (day=1 week=2 month=3 year=4)
 *   safesearch                            u8 (off=0 moderate=1 strict=2)
 *   engines                               0x00 when None
 *                                         | 0x01 + u32le count + sorted, deduped,
 *                                           length-prefixed engine ids
 * ```
 *
 * Engine ids are sorted before hashing, so the key is stable under
 * permutation of `engines`. `engines = None` is *not* the same key as
 * `engines = Some(<default set>)`: the option tag byte differs, which is the
 * pinned-engines rule — an explicit pin never shares a cache entry with the
 * default fan-out.
 *
 * # Examples
 *
 * ```
 * use cauce_core::{CacheKey, ClientKind, EngineId, SafeSearch, SearchRequest};
 *
 * let req = SearchRequest {
 *     q: "tanstack router".into(),
 *     page: 1,
 *     lang: None,
 *     time_range: None,
 *     safesearch: SafeSearch::Off,
 *     engines: None,
 *     client: ClientKind::Api,
 *     origin: cauce_core::SearchOrigin::User,
 * };
 *
 * // engines=None twice is equal.
 * assert_eq!(CacheKey::from(&req), CacheKey::from(&req));
 *
 * // engines=None vs engines=Some(<default set>) is NOT equal: a pinned
 * // request gets its own cache entries.
 * let mut pinned = req.clone();
 * pinned.engines = Some(vec![EngineId::from("bing"), EngineId::from("brave")]);
 * assert_ne!(CacheKey::from(&req), CacheKey::from(&pinned));
 *
 * // Engine order does not matter.
 * let mut permuted = req.clone();
 * permuted.engines = Some(vec![EngineId::from("brave"), EngineId::from("bing")]);
 * assert_eq!(CacheKey::from(&pinned), CacheKey::from(&permuted));
 * ```
 */
export type CacheKey = string;
