// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheKey } from "./CacheKey";
import type { EngineId } from "./EngineId";
import type { SearchResponse } from "./SearchResponse";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A `cache_entries` row (parent plan section 5).
 *
 * `get_exact` only returns rows where `expires_at` is still in the future;
 * `get_cache` (admin route) returns the row regardless.
 */
export type CachedSearch = { key: CacheKey, 
/**
 * The query as stored (`response.query` normalised form is in `params`).
 */
query: string, 
/**
 * Request parameters that produced this entry (`params_json` column).
 */
params: JsonValue, 
/**
 * Stored payload (`payload_json` column, decoded).
 */
response: SearchResponse, created_at: string, expires_at: string, 
/**
 * Number of times this row served a hit.
 */
hits: number, 
/**
 * Engines that produced the stored response (`engines_json` column).
 */
engines: Array<EngineId>, };
