// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LexicalConfig } from "./LexicalConfig";

/**
 * `[cache]`: cache-tier behaviour beyond TTLs (those live in `[search]`).
 */
export type CacheConfig = { 
/**
 * `[cache.lexical]`: the tier-2 FTS lookup (W1-10).
 */
lexical: LexicalConfig, 
/**
 * Seconds past `expires_at` a tier-1 row may still be served stale
 * while a deduped background refresh re-fetches it (W3-02).
 * `0` disables the stale serve; expired rows are only evicted once
 * they are older than this window.
 */
stale_grace_s: number, 
/**
 * TTL (seconds) applied to a response whose fan-out was partial —
 * any engine `Failed` or the deadline hit (W3-02): a degraded
 * answer never earns the full `search.ttl_s`.
 */
degraded_ttl_s: number, };
