// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CachedSearch } from "./CachedSearch";

/**
 * Shared cache listing logic for the JSON API and `/cache` page. The page
 * requests one additional unfiltered row to determine whether a next page
 * exists; parsing, filter semantics, limits, and store selection remain
 * authoritative here for both surfaces.
 * `limit`/`offset`/`query` ride the HTMX pager shape (kept for the
 * `CacheListing` wire export); the JSON arm serializes `entries` only.
 */
export type CacheListing = { entries: Array<CachedSearch>, limit: number, offset: number, query: string | null, };
