// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityFlags } from "./CapabilityFlags";
import type { InstanceMode } from "./InstanceMode";
import type { Role } from "./Role";

/**
 * `GET /api/capabilities` payload (plan §7.4): the mode, the caller's
 * role, and the feature flags the SPA renders by. `flags.adminSurface`
 * is role-relative (admins see the ops surfaces); the rest describe the
 * instance for every caller.
 */
export type Capabilities = { mode: InstanceMode, role: Role, flags: CapabilityFlags, };
