// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The capability flags under `Capabilities.flags` — kept a named wire
 * type so the ts-rs export preserves the §7.4 shape.
 */
export type CapabilityFlags = { 
/**
 * Whether the caller may mount the admin surfaces (`/app/admin`,
 * the ops `/api/*` routes). `role == admin`.
 */
adminSurface: boolean, 
/**
 * Whether the server keeps per-user search/answer history
 * (`search_log`/`answer_log`/`clicks`). Local mode only.
 */
serverHistory: boolean, 
/**
 * Whether the archive surfaces (`POST /api/pages`, `/app/archive`)
 * are live — `archive.enabled` AND a built fetcher.
 */
archiving: boolean, 
/**
 * Whether aggregate stats dashboards read server-wide telemetry.
 * Local mode only — a public dashboard shows the instance card.
 */
sharedStats: boolean, 
/**
 * PUB-03: whether `POST /api/answer` honours per-request BYOK
 * credential overrides (`[ai].allow_user_keys` — api_key/model/
 * protocol).
 */
allowUserKeys: boolean, 
/**
 * PUB-03: whether `POST /api/answer` also honours `ai.base_url`
 * overrides (`[ai].allow_user_base_url`).
 */
allowUserBaseUrl: boolean, };
