// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";

/**
 * One case outcome for one engine — the auditable detail behind the
 * aggregate `domain_hit_at5`.
 */
export type CaseOutcome = { engine: EngineId, query: string, expect_domains_top5: Array<string>, 
/**
 * `hit` is `false` when the engine errored or returned fewer than the
 * expected domains in its top 5.
 */
hit: boolean, 
/**
 * Hosts of the engine's top-5 normalized URLs (may be shorter on error).
 */
top5_hosts: Array<string>, 
/**
 * Engine error or `no cassette` when the outcome is a miss for a reason
 * other than returned results.
 */
note?: string | null, };
