// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheKey } from "./CacheKey";
import type { ClientKind } from "./ClientKind";

/**
 * `clicks` row (section 5). Also the `POST /api/click` body: the beacon omits
 * `id`, `ts` and `client`, which the server fills.
 */
export type ClickRow = { id: number | null, 
/**
 * Server always fills this on write; the serde default exists only so the
 * inbound beacon body can omit it.
 */
ts: string, 
/**
 * `CacheKey` of the search that produced the clicked result, when the
 * client knows it.
 */
query_hash: CacheKey | null, url: string, title: string, 
/**
 * 0-based position in the result list that was clicked. Beacons sent
 * through form-flattening extensions (htmx `json-enc`) stringify scalars,
 * so `"0"` and `0` are both accepted.
 */
position: number, client: ClientKind, };
