// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdmissionConfig } from "./AdmissionConfig";
import type { AiConfig } from "./AiConfig";
import type { ArchiveConfig } from "./ArchiveConfig";
import type { AuthConfig } from "./AuthConfig";
import type { CacheConfig } from "./CacheConfig";
import type { EngineEntry } from "./EngineEntry";
import type { HealthConfig } from "./HealthConfig";
import type { LogsConfig } from "./LogsConfig";
import type { MergeConfig } from "./MergeConfig";
import type { MetaConfig } from "./MetaConfig";
import type { SearchConfig } from "./SearchConfig";
import type { ServerConfig } from "./ServerConfig";
import type { UiConfig } from "./UiConfig";

/**
 * `PUT /api/config` response: the effective config, redacted (same
 * shape as `GET /api/config`), plus the `applied` /
 * `requires_restart` partition of the paths that changed.
 */
export type ConfigPutResponse = { 
/**
 * Dotted paths hot-applied in place.
 */
applied: Array<string>, 
/**
 * Dotted paths that take effect on the next `cauce serve` start.
 */
requires_restart: Array<string>, 
/**
 * `!requires_restart.is_empty()` — the flag the UI shows.
 */
effective_after_restart: boolean, 
/**
 * `[server]` section.
 */
server: ServerConfig, 
/**
 * `[search]` section.
 */
search: SearchConfig, 
/**
 * `[admission]` section.
 */
admission: AdmissionConfig, 
/**
 * `[health]` section.
 */
health: HealthConfig, 
/**
 * `[cache]` section.
 */
cache: CacheConfig, 
/**
 * `[merge]` section.
 */
merge: MergeConfig, 
/**
 * `[logs]` section.
 */
logs: LogsConfig, 
/**
 * `[ai]` section.
 */
ai: AiConfig, 
/**
 * `[archive]` section.
 */
archive: ArchiveConfig, 
/**
 * `[auth]` section.
 */
auth: AuthConfig, 
/**
 * `[ui]` section.
 */
ui: UiConfig, 
/**
 * `[[engines]]` entries plus the built-ins (`replay`, `ddgs`).
 */
engines: Array<EngineEntry>, 
/**
 * `[config]` section.
 */
config: MetaConfig, };
