// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdmissionConfig } from "./AdmissionConfig";
import type { AiConfig } from "./AiConfig";
import type { ArchiveConfig } from "./ArchiveConfig";
import type { AuthConfig } from "./AuthConfig";
import type { CacheConfig } from "./CacheConfig";
import type { EdgeConfig } from "./EdgeConfig";
import type { EngineEntry } from "./EngineEntry";
import type { HealthConfig } from "./HealthConfig";
import type { LogsConfig } from "./LogsConfig";
import type { MergeConfig } from "./MergeConfig";
import type { MetaConfig } from "./MetaConfig";
import type { RateLimitConfig } from "./RateLimitConfig";
import type { SearchConfig } from "./SearchConfig";
import type { ServerConfig } from "./ServerConfig";
import type { UiConfig } from "./UiConfig";

/**
 * The resolved configuration: defaults < TOML file < `CAUCE_*` env.
 *
 * Besides the typed sections it keeps the raw (pre-interpolation) file
 * tree for `save` and a map of template paths for redacted display; none
 * of that is part of the TOML schema (`#[serde(skip)]`).
 *
 * `Debug` and `Serialize` are manual: both emit the *redacted* view
 * (`display_tree`), so a resolved secret (e.g. `ai.api_key` from
 * `${env:PROVIDER_API_KEY}`) can never leak through `format!("{cfg:?}")`,
 * `serde_json::to_string(&cfg)` or a debug log line.
 */
export type Config = { 
/**
 * `[server]` section.
 */
server: ServerConfig, 
/**
 * `[search]` section.
 */
search: SearchConfig, 
/**
 * `[admission]` section.
 */
admission: AdmissionConfig, 
/**
 * `[health]` section.
 */
health: HealthConfig, 
/**
 * `[cache]` section.
 */
cache: CacheConfig, 
/**
 * `[merge]` section.
 */
merge: MergeConfig, 
/**
 * `[logs]` section.
 */
logs: LogsConfig, 
/**
 * `[ai]` section.
 */
ai: AiConfig, 
/**
 * `[archive]` section.
 */
archive: ArchiveConfig, 
/**
 * `[auth]` section.
 */
auth: AuthConfig, 
/**
 * `[rate_limit]` section (PUB-01).
 */
rate_limit: RateLimitConfig, 
/**
 * `[edge]` section (PUB-01).
 */
edge: EdgeConfig, 
/**
 * `[ui]` section.
 */
ui: UiConfig, 
/**
 * `[[engines]]` entries plus the built-ins (`replay`, `ddgs`).
 */
engines: Array<EngineEntry>, 
/**
 * `[config]` section.
 */
config: MetaConfig, };
