// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[edge]` (PUB-01): the shared-cache headers stamped on routes whose
 * [`cauce_server`] table row is `cache: shared` — the req/month lever
 * that lets a free CDN tier serve repeat `/api/search` hits without
 * touching the origin. Rows marked `private` get `private, no-store`
 * so an operator's "cache everything" edge rule cannot leak an
 * auth-varying or admin response.
 */
export type EdgeConfig = { 
/**
 * Stamp `Cache-Control` at all. `false` emits no header (the edge
 * then falls back to its own defaults). Read live per request.
 */
enabled: boolean, 
/**
 * `max-age`/`s-maxage`/`stale-while-revalidate` seconds on shared
 * rows. 60s is enough to collapse a flash crowd — repeat queries
 * inside a minute never reach the origin — while staying far
 * fresher than the store's own search TTL.
 */
ttl_s: number, };
