// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[engines.egress]` (a sub-table of an `[[engines]]` entry): upstream
 * egress and politeness policy for that engine's HTTP calls (W1-01).
 * Absent means a direct connection with a token bucket of 1 req/s,
 * burst 3 (settled inputs).
 */
export type EgressConfig = { 
/**
 * Static proxy URL (`http://`, `https://`, `socks5://`,
 * `socks5h://`). Absent = direct.
 */
proxy?: string | null, 
/**
 * Token-bucket refill rate in requests per second (>= 1).
 */
requests_per_second: number, 
/**
 * Token-bucket burst capacity (>= 1).
 */
burst: number, };
