// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EgressConfig } from "./EgressConfig";
import type { EngineId } from "./EngineId";
import type { EngineKind } from "./EngineKind";

/**
 * One `[[engines]]` table. `command`/`args`/`env`/`cwd` describe the child
 * for `kind = "exec"`; `spec` points at the YAML file for
 * `kind = "declarative"`.
 *
 * Field order matters for TOML serialisation: scalars and plain arrays
 * first, the `egress`/`env` tables last.
 */
export type EngineEntry = { 
/**
 * Stable id (`ddgs`, `replay`, `bing`, ...).
 */
id: EngineId, 
/**
 * Runtime that executes this entry.
 */
kind: EngineKind, 
/**
 * Member of the default fan-out set unless `CAUCE_ENGINES` overrides.
 */
enabled: boolean, 
/**
 * Executable to spawn (`exec` kind; required there).
 */
command?: string | null, 
/**
 * Arguments for `command`.
 */
args?: Array<string>, 
/**
 * Working directory of the child; relative `args` resolve against it.
 */
cwd?: string | null, 
/**
 * YAML spec path (`declarative` kind).
 */
spec?: string | null, 
/**
 * Fan-out tier override (`Tier` serializes as 1/2/3).
 */
tier?: number, 
/**
 * Results per page the engine reports back.
 */
page_size?: number | null, 
/**
 * `[engines.egress]` sub-table: proxy and token-bucket policy.
 */
egress?: EgressConfig | null, 
/**
 * Extra environment on top of the inherited one (`exec` kind).
 */
env?: { [key in string]: string }, 
/**
 * `[engines.params]` table: static per-engine params forwarded to `exec`
 * children on every v2-protocol request (issue #88).
 */
params?: { [key in string]: string }, };
