// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakerState } from "./BreakerState";
import type { EngineId } from "./EngineId";
import type { PhaseStats } from "./PhaseStats";

/**
 * One `/api/stats` `engines[]` row (W1-09): the persisted `engine_health`
 * fields plus the in-process request metrics merged in by the HTTP
 * handler (`StatsSnapshot::merge_metrics`). Store impls fill only the
 * health fields; the metric fields stay zeroed until the merge.
 */
export type EngineStatsRow = { engine: EngineId, 
/**
 * EWMA latency in ms (`engine_health.ewma_ms`; 0 when unseen).
 */
ewma_ms: number, failures: number, breaker: BreakerState, breaker_until: string | null, last_ok_at: string | null, last_error: string | null, 
/**
 * Engine calls completed this process lifetime.
 */
requests: number, 
/**
 * Total results returned across calls.
 */
result_count: number, 
/**
 * Successful answers / requests * 100 (SearXNG reliability parity;
 * `no_results` answers count as successful).
 */
reliability_pct: number, 
/**
 * Whole-call percentiles (pipeline-observed latency).
 */
median_ms: number, p80_ms: number, p95_ms: number, 
/**
 * `cauce_engine_duration_ms{phase="http"}` samples (the fetch leg).
 */
http: PhaseStats, 
/**
 * `cauce_engine_duration_ms{phase="parse"}` samples (extraction).
 */
parse: PhaseStats, };
