// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakerState } from "./BreakerState";
import type { EngineId } from "./EngineId";

/**
 * One row of the shared `/api/engines` + `/engines` data plane: the live
 * health row plus every field an engines-page card renders.
 */
export type EngineView = { 
/**
 * `declarative` | `exec` | `replay`; `"-"` for health-only leftovers.
 */
kind: string, 
/**
 * Effective tier: the live engine's own, else the `[[engines]]`
 * override. Absent for health-only leftovers.
 */
tier: number | null, 
/**
 * Resolved `enabled` flag; engines live but absent from the resolved
 * config count as enabled.
 */
enabled: boolean, 
/**
 * The resolved config names this engine (file entry or built-in).
 */
configured: boolean, 
/**
 * Live in the running pipeline's fan-out set.
 */
live: boolean, 
/**
 * When the breaker next admits a probe — `breaker_until` for an
 * `Open` engine, when either the next gated request or the
 * background recovery prober (issue #227) picks it up. Absent for
 * `Closed`/`HalfOpen` rows, where no probe is pending.
 */
next_probe_at: string | null, 
/**
 * Whole-call p95 from the in-process metrics registry (W1-09);
 * absent until the engine has served a request this process.
 */
p95_ms: number | null, 
/**
 * `ok / requests * 100` from the same registry; same absent-until-seen
 * rule as `p95_ms`.
 */
reliability_pct: number | null, 
/**
 * Searches that named this engine since UTC midnight (`search_log`).
 */
requests_today: number, engine: EngineId, 
/**
 * EWMA latency in ms (`alpha = 0.3`, section 4.4.6).
 */
ewma_ms: number, 
/**
 * Consecutive failure counter.
 */
failures: number, breaker: BreakerState, 
/**
 * Open breaker re-closes (to half-open) at this instant.
 */
breaker_until: string | null, last_ok_at: string | null, 
/**
 * Last `EngineError` rendered for display.
 */
last_error: string | null, };
