// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier of a search engine (`bing`, `brave`, `ddgs`, `replay`, ...).
 *
 * Serializes as a plain string on the wire and in `engines_json` columns.
 */
export type EngineId = string;
