// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";
import type { EngineStatus } from "./EngineStatus";

/**
 * Per-engine report of a fan-out: status, observed latency, result count.
 */
export type EngineReport = { engine: EngineId, status: EngineStatus, latency_ms: number, result_count: number, };
