// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakerState } from "./BreakerState";
import type { EngineId } from "./EngineId";

/**
 * `engine_health` row (section 5): scheduler state across restarts.
 */
export type EngineHealthRow = { engine: EngineId, 
/**
 * EWMA latency in ms (`alpha = 0.3`, section 4.4.6).
 */
ewma_ms: number, 
/**
 * Consecutive failure counter.
 */
failures: number, breaker: BreakerState, 
/**
 * Open breaker re-closes (to half-open) at this instant.
 */
breaker_until: string | null, last_ok_at: string | null, 
/**
 * Last `EngineError` rendered for display.
 */
last_error: string | null, };
