// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/engines/{id}/enable|disable` acknowledgement.
 */
export type EngineToggleAck = { 
/**
 * The toggled engine id.
 */
id: string, 
/**
 * The resolved `enabled` flag now persisted.
 */
enabled: boolean, 
/**
 * `true` when the pipeline did not rebuild in place and the flag
 * applies on the next `cauce serve` start.
 */
effective_after_restart: boolean, };
