// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";

/**
 * Per-engine score row of the report.
 */
export type EngineScore = { engine: EngineId, 
/**
 * Cases naming this engine.
 */
cases: number, 
/**
 * Cases where an expected domain appeared in the top 5.
 */
hits: number, 
/**
 * `hits / cases` — 0 when `cases` is 0.
 */
domain_hit_at5: number, 
/**
 * Threshold applied from `evals/thresholds.toml`.
 */
threshold: number, 
/**
 * `domain_hit_at5 >= threshold`.
 */
ok: boolean, };
