// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseOutcome } from "./CaseOutcome";
import type { EngineId } from "./EngineId";
import type { EngineScore } from "./EngineScore";

/**
 * The `evals/results/<date>-engines.json` artifact.
 */
export type EvalReport = { 
/**
 * Always `"engines"` — future eval kinds get their own suffix.
 */
kind: string, 
/**
 * `YYYY-MM-DD` — the filename stem.
 */
date: string, generated_at: string, 
/**
 * `true` for a `--live` run (real engines), `false` for replay
 * cassettes.
 */
live: boolean, 
/**
 * Per-engine aggregates, sorted by engine id.
 */
engines: Array<EngineScore>, 
/**
 * Engine ids below their threshold — feeds the workflow's single
 * tracking issue.
 */
below_threshold: Array<EngineId>, 
/**
 * One row per (case, engine) pair.
 */
outcomes: Array<CaseOutcome>, };
