// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[health]`: circuit-breaker knobs (W3-07, issue #227). The other
 * breaker rules (`RateLimited`/`Blocked` abuse window, the timeout
 * streak) stay settled constants on `HealthPolicy`; this section holds
 * the degraded pair — `degraded_threshold` consecutive
 * `Parse`/`Transport` errors open the breaker for `degraded_window_s`
 * seconds — plus the recovery trio: a failed half-open probe re-opens
 * for an adaptive window starting at `probe_window_s` and doubling to
 * `probe_window_max_s`, while `probe_tick_s` sets how often the
 * background prober claims due probes (0 disables it).
 */
export type HealthConfig = { 
/**
 * Consecutive `Parse`/`Transport` errors that open the breaker
 * (default 5). Must be >= 1: `0` would fire on the very first error
 * instead of being a streak.
 */
degraded_threshold: number, 
/**
 * Seconds the breaker stays open once the degraded streak trips it
 * (default 600) — also the ceiling on the re-open window for a
 * half-open probe that fails with `Parse`/`Transport`. `0` makes
 * the breaker never stay open (it flips to `HalfOpen` on the next
 * gate).
 */
degraded_window_s: number, 
/**
 * First re-open window after a failed probe (default 30 s) — the
 * floor of the adaptive retry backoff, which doubles per
 * consecutive probe failure up to `probe_window_max_s` and is
 * jittered per engine. Must be >= 1: `0` would let every tick
 * re-probe a dead engine.
 */
probe_window_s: number, 
/**
 * Cap on the probe retry backoff (default 300 s) — the longest a
 * consecutively-failing engine waits between probes, which caps
 * how often a dead endpoint is probed.
 */
probe_window_max_s: number, 
/**
 * Seconds between background recovery-prober passes (default 5).
 * `0` disables active probing: `Open -> HalfOpen` transitions then
 * only happen when a request happens to gate the engine.
 */
probe_tick_s: number, };
