// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerLogRow } from "./AnswerLogRow";
import type { ClickRow } from "./ClickRow";
import type { SearchLogRow } from "./SearchLogRow";

/**
 * One history item: a logged search, a click or an answer run, merged
 * newest-first by the route (`GET /api/history` reads one plane:
 * `search_log` + `clicks` + `answer_log`).
 */
export type HistoryItem = { "kind": "search" } & SearchLogRow | { "kind": "click" } & ClickRow | { "kind": "answer" } & AnswerLogRow;
