// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheKey } from "./CacheKey";

/**
 * `POST /api/pages` body: the URL to index plus, for the click beacon,
 * the `CacheKey` of the search that surfaced it.
 */
export type IndexBody = { url: string, query_hash: CacheKey | null, };
