// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/instance` payload: the public-mode dashboard card fields
 * plus the SPA bootstrap knobs `GET /api/config` used to carry (config
 * itself goes admin-only in public mode, so the bootstrap reads here).
 */
export type InstanceInfo = { 
/**
 * Display name (`server.name`, default `"cauce"`).
 */
name: string, 
/**
 * Build version (`CARGO_PKG_VERSION`).
 */
version: string, 
/**
 * Number of engines configured and enabled.
 */
engineCount: number, 
/**
 * Engine ids the SPA pin-checks its engine chips against.
 */
engineIds: Array<string>, 
/**
 * Whether `POST /api/answer` is live (`ai.enabled` + provider built).
 */
aiEnabled: boolean, 
/**
 * Whether the results-page click beacon posts indexing requests
 * (`archive.index_on_click` + a live archiver). Local mode only —
 * public-mode clicks index into the browser-local store instead.
 */
indexOnClick: boolean, };
