// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latency percentiles over `search_log.latency_ms` in the window (and the
 * in-process TTFR rolling window, W2-03).
 */
export type LatencyPercentiles = { p50_ms: number, p90_ms: number, p99_ms: number, };
