// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[cache.lexical]`: tier-2 acceptance gate (W1-10). On a tier-1 miss the
 * pipeline FTS-matches stored entries and serves the best-ranked row whose
 * query shares `threshold` of the request's tokens (Jaccard after
 * normalisation and stopword removal) under the same page/lang.
 */
export type LexicalConfig = { 
/**
 * Master switch for the tier-2 lookup.
 */
enabled: boolean, 
/**
 * Minimum Jaccard token similarity to accept a hit. Must be finite
 * and in `(0.0, 1.0]`; `Config::load` rejects anything else.
 */
threshold: number, };
