// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[logs]`: JSONL log retention (W0-05 consumes `retention_days`).
 */
export type LogsConfig = { 
/**
 * Days a `logs/cauce-YYYY-MM-DD.jsonl` file is kept.
 */
retention_days: number, };
