// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[merge]` section: RRF merge tuning (W3-03). The reliability weight
 * itself is not a knob — it is computed from engine health; this section
 * holds the RRF constant and the host-diversity cap.
 */
export type MergeConfig = { 
/**
 * The RRF constant: `score += weight / (rrf_k + rank)` per engine.
 * Must be finite and `>= 0.0`; `Config::load` rejects anything else.
 */
rrf_k: number, 
/**
 * Max merged results emitted per host — `m.`/`amp.` folds share the
 * host. `0` disables the collapse.
 */
collapse_same_host_after: number, };
