// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheKey } from "./CacheKey";

/**
 * One `pages` row (W5-01): a fetched page, readability-extracted to
 * markdown. The only writer is `archive::Archiver::fetch_and_index`.
 */
export type PageRow = { 
/**
 * Normalized final URL (the `pages` primary key).
 */
url: string, 
/**
 * When the page was fetched and indexed.
 */
fetched_at: string, 
/**
 * Readability title; may be empty when the page carries none.
 */
title: string, 
/**
 * Article body as markdown (at most `archive::MAX_MARKDOWN_BYTES`).
 */
markdown: string, 
/**
 * Bytes of HTML read from the network (post-cap: `<= MAX_FETCH_BYTES`).
 */
byte_len: number, 
/**
 * `CacheKey` of the search the page was clicked from (UI click
 * beacon); `None` for direct `POST /api/pages` and MCP calls.
 */
source_query_hash: CacheKey | null, };
