// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `DELETE /api/pages/{url}` acknowledgement: echoes the normalized key
 * the row was stored under (`{"deleted":true,"url":...}`).
 */
export type PageDeleteAck = { deleted: boolean, 
/**
 * Normalized URL key the deleted row was stored under.
 */
url: string, };
