// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Median/p80/p95 of a millisecond sample window (engine phases, admission
 * waits). Zeroed when no samples exist — percentiles are always numbers on
 * the wire (the W1-09 acceptance contract).
 */
export type PhaseStats = { median_ms: number, p80_ms: number, p95_ms: number, };
