// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[rate_limit]` (PUB-01): a per-client-IP token bucket in front of
 * the `/api/*` + `/mcp` surfaces. It exists for public instances — the
 * embedded UI and redirects are cheap, so only the expensive API work
 * counts. Loopback peers and `Authorization: Bearer <admin token>`
 * requests are exempt.
 */
export type RateLimitConfig = { 
/**
 * On/off. Unset means "on when `server.public_instance`" — a public
 * instance gets protection without the operator remembering a
 * second flag; `enabled = false` opts out explicitly.
 */
enabled?: boolean | null, 
/**
 * Sustained quota per key, requests per second.
 */
requests_per_second: number, 
/**
 * Token-bucket burst per key — absorbs a page load's worth of API
 * calls without tripping.
 */
burst: number, 
/**
 * Trust `CF-Connecting-IP` / the leftmost `X-Forwarded-For` hop as
 * the client key. Only safe behind a proxy that sets/strips those
 * headers; off by default so a direct-exposed instance cannot be
 * spoofed into another client's bucket.
 */
trust_proxy_headers: boolean, 
/**
 * Optional single header to read the client key from, overriding
 * the default `CF-Connecting-IP` → `X-Forwarded-For` order. Needed
 * by chained-CDN deployments (e.g. a Pages Function re-fetching
 * through a second CF edge, where `CF-Connecting-IP` arrives as
 * the function's egress IP and the caller's real IP is only in
 * `X-Forwarded-For`). The leftmost hop is used; only consulted
 * when `trust_proxy_headers` is on.
 */
client_ip_header?: string | null, };
