// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedactionProfile } from "./RedactionProfile";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The export document (`cauce-report-<ts>.json`, `v = 1`): the fixed
 * envelope plus one flattened entry per registered section, so
 * `cauce`, `config`, `stats`, ... sit beside the envelope keys.
 */
export type ReportBundle = { 
/**
 * Schema version — always [`SCHEMA_VERSION`].
 */
v: number, 
/**
 * The profile this bundle was built (and already redacted) under.
 */
profile: RedactionProfile, 
/**
 * When the export was assembled.
 */
generated_at: string, 
/**
 * Owner free-text, never auto-filled.
 */
notes: string, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
