// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";
import type { StreamResult } from "./StreamResult";

/**
 * The `results` SSE event payload of `GET /api/search/stream` (W2-01):
 * one engine's raw batch (pre-merge) plus the request-elapsed ms.
 */
export type ResultsFrame = { engine: EngineId, results: Array<StreamResult>, elapsed_ms: number, };
