// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The caller's role on this request — `admin` when the request carries a
 * configured admin token (or the instance is local), `user` otherwise.
 */
export type Role = "admin" | "user";
