// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who originated a stored row (`origin` column / `?origin=` filter,
 * #254): `user` = typed into the UI; `agent` = an answer-loop tool
 * call or any api/mcp/cli client. The stored value is resolved at
 * write time ([`SearchRequest::resolved_origin`]) — a request cannot
 * claim `user` over the wire.
 */
export type SearchOrigin = "user" | "agent";
