// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[search]`: pipeline tunables (parent plan sections 3 and 4.4).
 */
export type SearchConfig = { 
/**
 * Hard fan-out deadline in milliseconds.
 */
deadline_ms: number, 
/**
 * Results wanted before the hedge point is considered satisfied.
 */
min_results: number, 
/**
 * Earliest tier-2 hedge point in ms (W3-01): tier-1 gets at least
 * this long to answer before the hedge can fire.
 */
hedge_floor_ms: number, 
/**
 * Latest tier-2 hedge point in ms (W3-01): a slow tier-1 history
 * never delays the hedge past this.
 */
hedge_ceiling_ms: number, 
/**
 * Default cache TTL in seconds.
 */
ttl_s: number, 
/**
 * Upper bound for per-request `ttl_s` overrides.
 */
ttl_cap_s: number, };
