// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheKey } from "./CacheKey";
import type { ClientKind } from "./ClientKind";
import type { EngineId } from "./EngineId";
import type { LogSource } from "./LogSource";
import type { SearchOrigin } from "./SearchOrigin";

/**
 * `search_log` row (section 5). Written unconditionally for every request,
 * cache hit or not. `id` is `None` on insert and `Some` when read back.
 */
export type SearchLogRow = { id: number | null, ts: string, 
/**
 * The `CacheKey` of the request; joins to `clicks.query_hash`.
 */
query_hash: CacheKey, 
/**
 * The normalized query (`normalize_query`: lowercased, whitespace
 * collapsed). Stays normalized because stats grouping and the
 * history `q` filter depend on it.
 */
query: string, 
/**
 * The query text exactly as submitted (original casing and spacing),
 * for history displays. `None` on rows written before schema v2.
 */
query_raw: string | null, client: ClientKind, source: LogSource, 
/**
 * Cache tier that served the hit; `None` on `source = network`.
 * Serializes as the tier integer (1-3).
 */
tier: number | null, latency_ms: number, result_count: number, 
/**
 * Engines that actually ran (`engines_json` column). On cache-hit
 * rows (`source = cache`) this instead carries the engines that
 * *produced* the cached entry (provenance), not engines that ran for
 * this request.
 */
engines: Array<EngineId>, deadline_hit: boolean, 
/**
 * Who originated the search (`origin` column, #254): `user` for a
 * search typed into the UI, `agent` for answer-loop tool calls and
 * api/mcp/cli clients. `#[serde(default)]` keeps pre-column wire
 * payloads decodable.
 */
origin: SearchOrigin, };
