// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMeta } from "./SearchMeta";
import type { SearchResult } from "./SearchResult";

/**
 * The canonical `GET /api/search` payload (parent plan 4.2).
 */
export type SearchResponse = { 
/**
 * The query as executed (post-normalisation).
 */
query: string, results: Array<SearchResult>, meta: SearchMeta, };
