// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";
import type { EngineReport } from "./EngineReport";
import type { Source } from "./Source";

/**
 * Response metadata (parent plan 4.2). `request_id` is a UUIDv7 minted by the
 * inbound surface and echoed in `X-Request-Id` and the JSONL log.
 */
export type SearchMeta = { source: Source, engines_used: Array<EngineReport>, 
/**
 * Engine ids suppressed by an open breaker on this request (W2-01
 * amendment): collected at the fan-out gate and surfaced on the page
 * meta line and the SSE `meta` event. `default` keeps `payload_json`
 * rows written before the field existed decodable.
 */
engines_skipped: Array<EngineId>, 
/**
 * True when the hard deadline cancelled at least one engine call.
 */
deadline_hit: boolean, 
/**
 * True when the W3-01 hedge fired tier-2 engines on this request.
 * `default` keeps `payload_json` rows written before the field
 * existed decodable.
 */
hedged: boolean, 
/**
 * Elapsed ms at which the hedge fired; `None` when it did not.
 */
hedge_at_ms?: number | null, elapsed_ms: number, request_id: string, };
