// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[server]`: HTTP bind address. Loopback by default (settled inputs).
 */
export type ServerConfig = { 
/**
 * Bind host; `127.0.0.1` unless explicitly exposed.
 */
host: string, 
/**
 * Bind port; 4479 by default.
 */
port: number, 
/**
 * Canonical externally visible HTTP(S) origin for absolute browser URLs.
 * When unset, the effective bind host and port are used over HTTP.
 */
public_url: string | null, 
/**
 * FX-07 instance mode (SearXNG `server.public_instance` prior art):
 * `false` (default) is the single-user local mode — today's behavior
 * bit-for-bit. `true` marks the instance public: history and click
 * telemetry stop writing server-side, `GET /api/capabilities` reports
 * `mode: "public"`, and the admin `/api/*` surface requires an
 * `[auth] admin_tokens` bearer credential.
 */
public_instance: boolean, 
/**
 * Display name of this instance (the public-mode dashboard card and
 * `GET /api/instance` report it). `"cauce"` by default.
 */
name: string, };
