// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[server]`: HTTP bind address. Loopback by default (settled inputs).
 */
export type ServerConfig = { 
/**
 * Bind host; `127.0.0.1` unless explicitly exposed.
 */
host: string, 
/**
 * Bind port; 4479 by default.
 */
port: number, 
/**
 * Canonical externally visible HTTP(S) origin for absolute browser URLs.
 * When unset, the effective bind host and port are used over HTTP.
 */
public_url: string | null, };
