// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a response came from (parent plan 4.2, `meta.source`).
 *
 * Wire shape is externally tagged with snake_case variant names:
 * `{"cache":{"tier":1,"age_s":12,"ttl_s":3600,"stale":false}}` or `"network"`.
 * A fuzzy hit additionally carries `matched_query` (W1-10 tier-2 lexical,
 * W5-05 tier-3 semantic).
 */
export type Source = { "cache": { 
/**
 * Serializes as the tier integer (1-3).
 */
tier: number, 
/**
 * Seconds since the hit was stored.
 */
age_s: number, 
/**
 * Seconds until expiry (remaining TTL at serve time).
 */
ttl_s: number, 
/**
 * True when the row was past `expires_at` (served stale).
 */
stale: boolean, 
/**
 * The stored query a fuzzy tier (2 lexical, 3 semantic) matched.
 * Absent on an exact tier-1 hit, so the tier-1 wire shape is
 * unchanged.
 */
matched_query?: string | null, } } | "network";
