// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdmissionStats } from "./AdmissionStats";
import type { ClientCount } from "./ClientCount";
import type { DayCount } from "./DayCount";
import type { EngineStatsRow } from "./EngineStatsRow";
import type { EvalReport } from "./EvalReport";
import type { LatencyPercentiles } from "./LatencyPercentiles";
import type { QueryCount } from "./QueryCount";
import type { TierHit } from "./TierHit";

/**
 * Dashboard aggregates (`GET /api/stats?days`, section 5 search_log readers
 * plus the cache/engine panels).
 *
 * `hit_rate` is `cache_hits / searches` over `search_log`, never derived from
 * `cache_entries` (that was the v2 dashboard bug).
 */
export type StatsSnapshot = { window_days: number, searches: number, 
/**
 * Searches whose `source` was `cache`.
 */
cache_hits: number, hit_rate: number, 
/**
 * None when the window has no searches.
 */
latency: LatencyPercentiles | null, 
/**
 * TTFR percentiles (p50/p90/p99) over the in-process `cauce_ttfr_ms`
 * rolling window (W2-03). Filled by `merge_metrics`; `None` before the
 * first network search.
 */
ttfr: LatencyPercentiles | null, by_client: Array<ClientCount>, 
/**
 * Most frequent queries in the window, count descending (cap 10).
 */
top_queries: Array<QueryCount>, 
/**
 * Queries with `result_count = 0`, most frequent first.
 */
zero_result_queries: Array<string>, 
/**
 * Cache hits grouped by serving tier (W2-03 hit-rate-by-tier panel).
 */
hits_by_tier: Array<TierHit>, 
/**
 * Search outcome counts (`ok` / `error` / `rejected`) folded from
 * `cauce_search_requests_total`'s `outcome` label (W2-03 amendment).
 * Filled by `merge_metrics`; empty in store results.
 */
outcomes: Record<string, number>, 
/**
 * Searches in the window that hit the hard deadline
 * (`search_log.deadline_hit`). The windowed counterpart of the
 * lifetime `admission.deadline_hits` counter: the reliability panel
 * rates this against `searches`, never the lifetime counter, so
 * numerator and denominator share the window.
 */
deadline_hits: number, per_day: Array<DayCount>, 
/**
 * Engine table: one row per engine in `engine_health`, extended with
 * the in-process request metrics by `merge_metrics` (W1-09).
 */
engines: Array<EngineStatsRow>, 
/**
 * Live `cache_entries` rows (unexpired).
 */
cache_entries: number, 
/**
 * Rows past `expires_at` awaiting eviction.
 */
cache_entries_expired: number, 
/**
 * Database file size in bytes (`page_count * page_size`; 0 when the
 * store cannot report it).
 */
cache_db_bytes: number, 
/**
 * `created_at` of the newest `cache_entries` row.
 */
cache_newest_at: string | null, 
/**
 * Admission/queue aggregates. Zeroed by store impls; the HTTP handler
 * fills it from the in-process metrics registry via `merge_metrics`.
 */
admission: AdmissionStats, 
/**
 * The newest `evals/results/<date>-engines.json` run (W3-05), read by
 * the `/api/stats` handler on each request — `None` when no report
 * file exists. Store impls always emit `None`.
 */
engine_eval?: EvalReport | null, };
