// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineId } from "./EngineId";

/**
 * A [`SearchResult`] plus `key`, the client-side dedupe key
 * (`normalize_url` of its URL — the same form `meta.order` carries). The
 * progressive page dedupes appended articles on `key`: the merge drops
 * duplicate URL spellings the raw `url` field would render twice.
 */
export type StreamResult = { 
/**
 * Dedup key: `normalize_url` of `url`.
 */
key: string, url: string, title: string, snippet: string, 
/**
 * Engine that produced the row (before merge dedupe keeps the best score).
 */
engine: EngineId, 
/**
 * Publication timestamp when the engine reports one; RFC 3339 on the wire.
 */
published: string | null, 
/**
 * RRF score assigned by the merge; raw engine order otherwise.
 */
score: number, };
