// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /api/suggest` response, documented for the typed client
 * (FX-01): a fixed-length array `[term, completions]` where
 * `term` echoes the `q=` parameter verbatim and `completions` are the
 * prefix-matched suggestions — `['', []]` on an absent/blank `q`.
 * Heterogeneous tuples have no Rust-struct shape, so the wire type is
 * declared outright: `[string, string[]]`.
 */
export type SuggestResponse = [string, string[]];
