// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache hits served by one tier (`search_log.tier` on `source = 'cache'`
 * rows). The dashboard renders the per-tier hit rate as `hits / searches`.
 */
export type TierHit = { tier: number, hits: number, };
