// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[ui]`: page-shell settings. Only `locale` today — one embedded
 * catalog per build, picked at startup; per-request `Accept-Language`
 * negotiation is deliberately out of scope (TS migration step 2/3).
 */
export type UiConfig = { 
/**
 * Catalog name under `crates/cauce-server/locales/` (`en` ships).
 * An unknown locale falls back to `en` at lookup time.
 */
locale: string, };
