// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at <https://mozilla.org/MPL/2.0/>.

// /opensearch.xml: generated by the backend from its configured public
// origin, so it is proxied rather than templated at build time.

import { proxy, type PagesFn, type ProxyEnv } from "./_proxy";

export const onRequest: PagesFn<ProxyEnv> = ({ request, env }) =>
  proxy(request, env.API_ORIGIN);
