/**
 * Typed fetch client for the oxe backend, generated types + fixture layer.
 *
 * Wire types come from `src/lib/types.gen.ts` (generated by `openapi-typescript` from the
 * repo-root `openapi.json` — see the `gen:types` bun script and the `check:ts-types` mise
 * task for the drift gate). `openapi-fetch` types the request body, the query, the path
 * params and the response at each call site from the same `paths` object, per the plan's
 * "API contract is typed in both directions" section — there is no hand-written response
 * interface anywhere in this file.
 *
 * Base URL: relative/same-origin. In production, `app.frontend()` serves the built SPA from
 * the same FastAPI app that serves `/search`, so a relative `baseUrl` (empty string) just
 * works. In dev (`vite dev`, separate port from `uv run oxe`), point `VITE_API_BASE_URL` at
 * the backend dev port (e.g. `.env.local` with `VITE_API_BASE_URL=http://localhost:8000`) or
 * configure a Vite dev-server proxy for `/search` and `/health`; either way this file only
 * reads `import.meta.env.VITE_API_BASE_URL` and falls back to same-origin.
 */
import createClient from 'openapi-fetch'
import { parseFixtureParams } from './fixtures.ts'
import type { components, paths } from './types.gen.ts'

export type { ForcedState, FixtureParams } from './fixtures.ts'
export { fixturesEnabled, parseFixtureParams, forcedStateSchema, suggestSchema } from './fixtures.ts'

export type SearxResponse = components['schemas']['SearxResponse']
export type SearchQuery = paths['/search']['get']['parameters']['query']

const baseUrl = import.meta.env.VITE_API_BASE_URL ?? ''

export const client = createClient<paths>({ baseUrl })

/** Thrown by `search()` when `force=error` is active (day-0 gate 6, checkpoints 8 and 13). */
export class ForcedSearchError extends Error {
  constructor() {
    super('search forced to error via ?force=error (QA/dev fixture)')
    this.name = 'ForcedSearchError'
  }
}

/** Canned zero-results `SearxResponse`, valid-shaped, used by `force=empty`. */
export function emptySearxResponse(query: string): SearxResponse {
  return {
    query,
    number_of_results: 0,
    results: [],
    answers: [],
    corrections: [],
    infoboxes: [],
    suggestions: [],
    unresponsive_engines: [],
  }
}

/**
 * Typed wrapper around `GET /search` that honors the `force` QA fixture (checkpoints 7, 8,
 * 13, 14) before ever touching the network. `force` is only obeyed when
 * `fixturesEnabled()` is true (dev builds); in production the fixture check is a no-op and
 * every call reaches the real backend.
 *
 * - `force=error` -> rejects with `ForcedSearchError`.
 * - `force=empty` -> resolves with a canned zero-results `SearxResponse`, no network call.
 * - `force=ai-off` / `null` -> falls through to the real `openapi-fetch` call.
 */
export async function search(
  query: SearchQuery,
  urlSearchParams?: URLSearchParams,
): Promise<SearxResponse> {
  const { force } = urlSearchParams
    ? parseFixtureParams(urlSearchParams)
    : { force: null }

  if (force === 'error') {
    throw new ForcedSearchError()
  }
  if (force === 'empty') {
    return emptySearxResponse(query.q)
  }

  const { data, error } = await client.GET('/search', { params: { query } })
  if (error) {
    throw error
  }
  return data
}
