/**
 * Typed client wrappers for the history/dashboard endpoints: `GET /api/history` and
 * `GET /api/stats` (plus the `copy json` re-fetch of a past query via `GET /search`,
 * which lives in `api.ts`).
 *
 * Wire types come from `src/lib/types.gen.ts` (generated by `openapi-typescript` from the
 * repo-root `openapi.json`); `openapi-fetch` types the query params and responses at each
 * call site from the same `paths` object, per the ui/AGENTS.md wire-type rule. The shapes
 * below are pinned with type-level `Equal` assertions so drift between codegen output and
 * these call sites fails tsc.
 */
import type { components, paths } from './types.gen.ts'
import { client } from './api.ts'

type Equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false

/** One click row (`GET /api/history` items are clicks only — no cache entries). */
export type ClickItem = components['schemas']['ClickItem']
export const _pinClickItem: Equal<ClickItem, components['schemas']['ClickItem']> = true

/** `GET /api/history` response body. */
export type HistoryResponse = components['schemas']['HistoryResponse']
export const _pinHistoryResponse: Equal<
  HistoryResponse,
  components['schemas']['HistoryResponse']
> = true

/** `GET /api/stats` response body. */
export type StatsResponse = components['schemas']['StatsSummary']
export const _pinStatsResponse: Equal<StatsResponse, components['schemas']['StatsSummary']> = true

/** Query params for `GET /api/history` (hours-back window as string; absent/null = all time). */
export type HistoryQuery = NonNullable<paths['/api/history']['get']['parameters']['query']>

/**
 * Fetch the click history view (newest first) from `GET /api/history`. Throws on non-2xx.
 * The `since` param narrows to the schema's 24/168/720 hours enum; the backend returns
 * `since` as the same numeric enum (or `null` when absent) — callers needing "all time"
 * omit the param rather than sending a value.
 */
export async function history(query: HistoryQuery): Promise<HistoryResponse> {
  const { data, error } = await client.GET('/api/history', {
    params: { query: { since: query.since, q: query.q, limit: query.limit } },
  })
  if (error) {
    throw new Error(`/api/history failed (${JSON.stringify(error)})`)
  }
  return data
}

/**
 * Fetch the dashboard aggregates from `GET /api/stats`. The backend does not serve a
 * `cache` key (rows/unexpired/db size — dashboard.md's cache panel) yet, so screens must
 * treat missing/log-less deployments as the normal case, not an error — see
 * `dashboardHasLogData()`.
 */
export async function stats(days = 14): Promise<StatsResponse> {
  const { data, error } = await client.GET('/api/stats', { params: { query: { days } } })
  if (error) {
    throw new Error(`/api/stats failed (${JSON.stringify(error)})`)
  }
  return data
}

/**
 * Whether the search-log-derived dashboard panels have real data to show (dashboard.md:
 * log-less deployments render the muted "no search log data yet" placeholder instead).
 * A hit_rate.total of 0 across the window means the search_log table is empty or absent.
 */
export function dashboardHasLogData(stats: StatsResponse): boolean {
  return stats.hit_rate.total > 0
}
