/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Get */
        get: operations["search_get_search_get"];
        put?: never;
        /** Search Post */
        post: operations["search_post_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerFrame: components["schemas"]["StepFrame"] | components["schemas"]["DeltaFrame"] | components["schemas"]["SourcesFrame"] | components["schemas"]["DoneFrame"] | components["schemas"]["ErrorFrame"];
        /** AnswerSource */
        AnswerSource: {
            /**
             * Favicon
             * @default null
             */
            favicon: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * DeltaFrame
         * @description One chunk of streamed answer text.
         */
        DeltaFrame: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delta";
        };
        /**
         * DoneFrame
         * @description Terminal frame: the final answer, or a mid-stream model/quality failure.
         */
        DoneFrame: {
            /** Answer */
            answer: string;
            /** Cached */
            cached: boolean;
            /** Confidence */
            confidence: number;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** Model */
            model: string;
            /** Related Questions */
            related_questions?: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
        };
        /**
         * ErrorFrame
         * @description Terminal frame for a failure before any ``done`` frame could be built.
         */
        ErrorFrame: {
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Response body for the liveness check.
         */
        HealthStatus: {
            /** Status */
            status: string;
        };
        /**
         * Infobox
         * @description SearXNG infobox entry (Wikipedia-style side panel content).
         */
        Infobox: {
            /**
             * Content
             * @default
             */
            content: string;
            /** Id */
            id?: string | null;
            /** Img Src */
            img_src?: string | null;
            /** Infobox */
            infobox: string;
            /** Urls */
            urls?: components["schemas"]["InfoboxUrl"][];
        };
        /**
         * InfoboxUrl
         * @description One entry in an ``Infobox.urls`` list.
         */
        InfoboxUrl: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * SearchRequest
         * @description The canonical SearXNG-shaped search request.
         *
         *     Cache identity (``oxe.search.service.cache_key``) is computed on this
         *     model's fields, so the native ``/search`` route and the future Exa
         *     compat adapter -- which will build a ``SearchRequest`` from an
         *     Exa-shaped request before calling the service -- share one cache row
         *     for the same underlying query.
         */
        SearchRequest: {
            /** Categories */
            categories?: string[];
            /**
             * Language
             * @default all
             */
            language: string;
            /**
             * Pageno
             * @default 1
             */
            pageno: number;
            /** Q */
            q: string;
            /**
             * Safesearch
             * @default 0
             * @enum {integer}
             */
            safesearch: 0 | 1 | 2;
            /** Time Range */
            time_range?: ("day" | "week" | "month" | "year") | null;
        };
        /**
         * SearchResult
         * @description One canonical SearXNG-shaped search result.
         */
        SearchResult: {
            /**
             * Category
             * @default general
             */
            category: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Engine */
            engine: string;
            /** Engines */
            engines?: string[];
            /** Publisheddate */
            publishedDate?: string | null;
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * SearxResponse
         * @description The canonical SearXNG-shaped search response.
         *
         *     Two of these three rules from the plan's "search contract" section are
         *     enforced here as shape; the third (unresponsive_engines-with-no-results
         *     must raise, never be returned) is a service-level invariant, enforced in
         *     ``oxe/search/service.py`` rather than at the model layer, since a
         *     freshly-constructed response legitimately passes through this state
         *     while an engine is still composing partial results.
         */
        SearxResponse: {
            /** Answers */
            answers?: string[];
            /** Corrections */
            corrections?: string[];
            /** Infoboxes */
            infoboxes?: components["schemas"]["Infobox"][];
            /**
             * Number Of Results
             * @default 0
             */
            number_of_results: number;
            /** Query */
            query: string;
            /** Results */
            results?: components["schemas"]["SearchResult"][];
            /** Suggestions */
            suggestions?: string[];
            /** Unresponsive Engines */
            unresponsive_engines?: components["schemas"]["UnresponsiveEngine"][];
        };
        /**
         * SourcesFrame
         * @description The set of sources the answer drew on, once known.
         */
        SourcesFrame: {
            /** Sources */
            sources?: components["schemas"]["AnswerSource"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sources";
        };
        /**
         * StepFrame
         * @description A tool call the model is making (e.g. a web search) is starting.
         */
        StepFrame: {
            /** Label */
            label: string;
            /** Query */
            query: string;
            /** Tool */
            tool: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
        };
        /**
         * UnresponsiveEngine
         * @description One engine that failed to answer, per SearXNG's ``unresponsive_engines``.
         *
         *     SearXNG itself represents this as a two-element list; modelled here as
         *     a named pair so both entry points and tests reference ``.engine`` /
         *     ``.error`` rather than positional indices.
         */
        UnresponsiveEngine: {
            /** Engine */
            engine: string;
            /** Error */
            error: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    search_get_search_get: {
        parameters: {
            query: {
                /** @description Query text. */
                q: string;
                /** @description 1-based result page. */
                pageno?: number;
                /** @description SearXNG category names. */
                categories?: string[];
                /** @description Language code, or 'all'. */
                language?: string;
                /** @description Restrict to results published within this window. */
                time_range?: ("day" | "week" | "month" | "year") | null;
                /** @description 0=off, 1=moderate, 2=strict. */
                safesearch?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_post_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
