/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Click history feed.
         * @description Click rows newest-first plus the header stats line.
         *
         *     ``Query``'s ``ge``/``le`` bounds are a range, not a set, so in-range gap
         *     values (e.g. 48) reach the handler; ``_narrow_since`` turns them into a
         *     ``ValueError``, which FastAPI reports as 500 today. Only the three
         *     literal values (24/168/720) are schema-valid for clients, per the
         *     generated OpenAPI ``enum`` -- gap values are caller bugs, not user input.
         */
        get: operations["api_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard aggregates.
         * @description Aggregates over the search log (searches/day, hit rate, latency
         *     percentiles, top and zero-result queries, client split).
         */
        get: operations["api_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Get */
        get: operations["search_get_search_get"];
        put?: never;
        /** Search Post */
        post: operations["search_post_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerFrame: components["schemas"]["StepFrame"] | components["schemas"]["DeltaFrame"] | components["schemas"]["SourcesFrame"] | components["schemas"]["DoneFrame"] | components["schemas"]["ErrorFrame"];
        /** AnswerSource */
        AnswerSource: {
            /**
             * Favicon
             * @default null
             */
            favicon: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * ClickItem
         * @description One click row, newest-first in ``HistoryResponse.items``.
         */
        ClickItem: {
            /** Clicked At */
            clicked_at: number;
            /** Query */
            query: string;
            /** Query Hash */
            query_hash: string;
            /** Result Id */
            result_id: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ClientSplit */
        ClientSplit: {
            /** Client */
            client: string;
            /** Count */
            count: number;
        };
        /**
         * DeltaFrame
         * @description One chunk of streamed answer text.
         */
        DeltaFrame: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delta";
        };
        /**
         * DoneFrame
         * @description Terminal frame: the final answer, or a mid-stream model/quality failure.
         */
        DoneFrame: {
            /** Answer */
            answer: string;
            /** Cached */
            cached: boolean;
            /** Confidence */
            confidence: number;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** Model */
            model: string;
            /** Related Questions */
            related_questions?: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
        };
        /**
         * ErrorFrame
         * @description Terminal frame for a failure before any ``done`` frame could be built.
         */
        ErrorFrame: {
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description Response body for the liveness check.
         */
        HealthStatus: {
            /** Status */
            status: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["ClickItem"][];
            /** Limit */
            limit: number;
            /** Since */
            since: (24 | 168 | 720) | null;
            stats: components["schemas"]["HistoryStats"];
        };
        /**
         * HistoryStats
         * @description The stats line above the history table (history.md).
         */
        HistoryStats: {
            /** Last 24H */
            last_24h: number;
            /** Oldest */
            oldest: number | null;
            /** Total */
            total: number;
        };
        /** HitRate */
        HitRate: {
            /** Cache Hits */
            cache_hits: number;
            /** Rate */
            rate: number | null;
            /** Total */
            total: number;
        };
        /**
         * Infobox
         * @description SearXNG infobox entry (Wikipedia-style side panel content).
         */
        Infobox: {
            /**
             * Content
             * @default
             */
            content: string;
            /** Id */
            id?: string | null;
            /** Img Src */
            img_src?: string | null;
            /** Infobox */
            infobox: string;
            /** Urls */
            urls?: components["schemas"]["InfoboxUrl"][];
        };
        /**
         * InfoboxUrl
         * @description One entry in an ``Infobox.urls`` list.
         */
        InfoboxUrl: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** LatencyMs */
        LatencyMs: {
            /** P50 */
            p50: number | null;
            /** P90 */
            p90: number | null;
            /** P99 */
            p99: number | null;
        };
        /**
         * SearchRequest
         * @description The canonical SearXNG-shaped search request.
         *
         *     Cache identity (``oxe.search.service.cache_key``) is computed on this
         *     model's fields, so the native ``/search`` route and the future Exa
         *     compat adapter -- which will build a ``SearchRequest`` from an
         *     Exa-shaped request before calling the service -- share one cache row
         *     for the same underlying query.
         */
        SearchRequest: {
            /** Categories */
            categories?: string[];
            /**
             * Language
             * @default all
             */
            language: string;
            /**
             * Pageno
             * @default 1
             */
            pageno: number;
            /** Q */
            q: string;
            /**
             * Safesearch
             * @default 0
             * @enum {integer}
             */
            safesearch: 0 | 1 | 2;
            /** Time Range */
            time_range?: ("day" | "week" | "month" | "year") | null;
        };
        /**
         * SearchResult
         * @description One canonical SearXNG-shaped search result.
         */
        SearchResult: {
            /**
             * Category
             * @default general
             */
            category: string;
            /**
             * Content
             * @default
             */
            content: string;
            /** Engine */
            engine: string;
            /** Engines */
            engines?: string[];
            /** Publisheddate */
            publishedDate?: string | null;
            /**
             * Score
             * @default 0
             */
            score: number;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** SearchesPerDay */
        SearchesPerDay: {
            /** Cache */
            cache: number;
            /** Day */
            day: string;
            /** Network */
            network: number;
            /** Total */
            total: number;
        };
        /**
         * SearxResponse
         * @description The canonical SearXNG-shaped search response.
         *
         *     Two of these three rules from the plan's "search contract" section are
         *     enforced here as shape; the third (unresponsive_engines-with-no-results
         *     must raise, never be returned) is a service-level invariant, enforced in
         *     ``oxe/search/service.py`` rather than at the model layer, since a
         *     freshly-constructed response legitimately passes through this state
         *     while an engine is still composing partial results.
         */
        SearxResponse: {
            /** Answers */
            answers?: string[];
            /** Corrections */
            corrections?: string[];
            /** Infoboxes */
            infoboxes?: components["schemas"]["Infobox"][];
            /**
             * Number Of Results
             * @default 0
             */
            number_of_results: number;
            /** Query */
            query: string;
            /** Results */
            results?: components["schemas"]["SearchResult"][];
            /** Suggestions */
            suggestions?: string[];
            /** Unresponsive Engines */
            unresponsive_engines?: components["schemas"]["UnresponsiveEngine"][];
        };
        /**
         * SourcesFrame
         * @description The set of sources the answer drew on, once known.
         */
        SourcesFrame: {
            /** Sources */
            sources?: components["schemas"]["AnswerSource"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sources";
        };
        /** StatsSummary */
        StatsSummary: {
            /** Client Split */
            client_split: components["schemas"]["ClientSplit"][];
            /** Days */
            days: number;
            hit_rate: components["schemas"]["HitRate"];
            latency_ms: components["schemas"]["LatencyMs"];
            /** Searches Per Day */
            searches_per_day: components["schemas"]["SearchesPerDay"][];
            /** Top Queries */
            top_queries: components["schemas"]["TopQuery"][];
            /** Zero Result Queries */
            zero_result_queries: components["schemas"]["ZeroResultQuery"][];
        };
        /**
         * StepFrame
         * @description A tool call the model is making (e.g. a web search) is starting.
         */
        StepFrame: {
            /** Label */
            label: string;
            /** Query */
            query: string;
            /** Tool */
            tool: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
        };
        /** TopQuery */
        TopQuery: {
            /** Count */
            count: number;
            /** Query */
            query: string;
        };
        /**
         * UnresponsiveEngine
         * @description One engine that failed to answer, per SearXNG's ``unresponsive_engines``.
         *
         *     SearXNG itself represents this as a two-element list; modelled here as
         *     a named pair so both entry points and tests reference ``.engine`` /
         *     ``.error`` rather than positional indices.
         */
        UnresponsiveEngine: {
            /** Engine */
            engine: string;
            /** Error */
            error: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ZeroResultQuery */
        ZeroResultQuery: {
            /** Last Seen */
            last_seen: number;
            /** Query */
            query: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_history_api_history_get: {
        parameters: {
            query?: {
                /** @description Hours back: 24=day, 168=week, 720=month; absent = all time. */
                since?: string | null;
                /** @description Query-text substring filter. */
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_stats_api_stats_get: {
        parameters: {
            query?: {
                /** @description Aggregation window in days. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    search_get_search_get: {
        parameters: {
            query: {
                /** @description Query text. */
                q: string;
                /** @description 1-based result page. */
                pageno?: number;
                /** @description SearXNG category names. */
                categories?: string[];
                /** @description Language code, or 'all'. */
                language?: string;
                /** @description Restrict to results published within this window. */
                time_range?: ("day" | "week" | "month" | "year") | null;
                /** @description 0=off, 1=moderate, 2=strict. */
                safesearch?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_post_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
